name: ${project.name}
main: com.squareblob.civworldeditutils.CivWorldEditUtils
version: ${project.version}
authors:
  - Squareblob
depend:
  - WorldEdit
  - Citadel
  - Bastion
description: Simple and hacky commands to make it easier to use Civ plugins with WorldEdit
api-version: 1.16
commands:
  setreinforcement:
    aliases:
      - setrein
    usage: /setreinforcement [mask] [group] <material=?> <health=?>
    description: Set the reinforcement of blocks matching given mask
    min-args: 2
    max-args: 100
    player-only: true
    permission: citadelutil.admin
  setreinforcementpreset:
    aliases:
      - setreinpreset
    usage: /setreinforcementpreset [presetName] <groupA> ... <groupZ>
    description: Run a list of reinforcement commands specified in config.yml
    min-args: 2
    max-args: 100
    player-only: true
    permission: citadelutil.admin
  setbastion:
    usage: /setbastion [mask] [bastiontype]
    description: Create pending bastions for blocks matching a given mask in current WorldEdit selection
    min-args: 2
    max-args: 100
    player-only: true
    permission: citadelutil.admin
  replacereinforcedblocks:
    aliases:
      - replacereinblocks
    usage: /replacereinforcedblocks [group] [pattern]
    description: Replace blocks reinforced to a given group in current WorldEdit selection with a block pattern selection
    min-args: 2
    max-args: 100
    player-only: true
    permission: citadelutil.admin
permissions:
  civworldeditutils.admin:
    default: op
