name: CivWorldEditUtils
main: com.squareblob.civworldeditutils.CivWorldEditUtils
version: ${project.version}
authors:
  - Squareblob
depend:
  - WorldEdit
  - Citadel
  - Bastion
  - NameLayer
description: Simple and hacky commands to make it easier to use Civ plugins with WorldEdit
api-version: 1.18
permissions:
  civworldeditutils.admin:
    default: op
